### ISSUE TITLE
Redundant lines of code, suggestion, and question

### ISSUE THREAD

**Issue by jakewilliami** [joshy/striprtf#18]
Hi there!

Neat little package you have here.  Thank you :-)

I was wondering, are lines [143](https://github.com/joshy/striprtf/blob/master/striprtf/striprtf.py#L143) and [153](https://github.com/joshy/striprtf/blob/master/striprtf/striprtf.py#L153) redundant?  On that note, in [this](https://github.com/joshy/striprtf/blob/master/striprtf/striprtf.py#L98-L105) `try` block, could you not just do
```python3
if stack:
    ucskip, ignorable = stack.pop()
else:
    ucskip = 0
    ignorable = True
```
This might be more performant than a `try` block.

I was also wondering, would you mind if I ported this logic into another language?

All the best!

**Comment by joshy** [comment]
Hi,

thanks for the suggestions, make sense to me. About the [if else](https://github.com/joshy/striprtf/blob/68d1b31d4e1b0035628115ad2e367c7775f546af/striprtf/striprtf.py#L140), that could be just omitted because in both cases it is doing the same thing. Also [here](https://github.com/joshy/striprtf/blob/68d1b31d4e1b0035628115ad2e367c7775f546af/striprtf/striprtf.py#L150). I will make a new release with the suggested changes soon.

Please go ahead and port it to another language.

All the best!
